version: '3'

services:
  bitbucket_node_1:
    depends_on:
      - postgresql
    build:
      context: .
      args:
        BITBUCKET_VERSION: ${BITBUCKET_VERSION}
    networks:
      - bbnet
    hostname: ${BITBUCKET_NODE1_HOSTNAME}
    volumes:
      - ${BITBUCKET_HOST_SHARED_DIR}:${BITBUCKET_SHARED_DIR}
      - ${XAUTH}:${XAUTH}
    ports:
      - ${BITBUCKET_NODE1_HTTP_PORT}:7990
      - ${BITBUCKET_NODE1_HAZELCAST_PORT}:5701
      - ${BITBUCKET_NODE1_DEBUG_PORT}:5005
    environment:
      - 'ELASTICSEARCH_ENABLED=false'
      - 'JDBC_URL=jdbc:postgresql://postgresql:5432/bitbucketdb'
      - JDBC_USER=${BITBUCKET_DB_USER}
      - JDBC_PASSWORD=${BITBUCKET_DB_PASS}
      - 'JDBC_DRIVER=org.postgresql.Driver'
      - 'JVM_MINIMUM_MEMORY=2048m'
      - 'JVM_MAXIMUM_MEMORY=4096m'
      - 'JVM_SUPPORT_RECOMMENDED_ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
      - HAZELCAST_GROUP_NAME=${BITBUCKET_HAZELCAST_GROUP_NAME}
      - 'HAZELCAST_GROUP_PASSWORD=1234'
      - 'HAZELCAST_NETWORK_MULTICAST=true'
      - XAUTHORITY=${XAUTH}
      - DISPLAY
  bitbucket_node_2:
    depends_on:
      - postgresql
    build:
      context: .
      args:
        BITBUCKET_VERSION: ${BITBUCKET_VERSION}
    networks:
      - bbnet
    hostname: ${BITBUCKET_NODE2_HOSTNAME}
    volumes:
      - ${BITBUCKET_HOST_SHARED_DIR}:${BITBUCKET_SHARED_DIR}
      - ${XAUTH}:${XAUTH}
    ports:
      - ${BITBUCKET_NODE2_HTTP_PORT}:7990
      - ${BITBUCKET_NODE2_HAZELCAST_PORT}:5701
      - ${BITBUCKET_NODE2_DEBUG_PORT}:5005
    environment:
      - 'ELASTICSEARCH_ENABLED=false'
      - 'JDBC_URL=jdbc:postgresql://postgresql:5432/bitbucketdb'
      - JDBC_USER=${BITBUCKET_DB_USER}
      - JDBC_PASSWORD=${BITBUCKET_DB_PASS}
      - 'JDBC_DRIVER=org.postgresql.Driver'
      - 'JVM_MINIMUM_MEMORY=2048m'
      - 'JVM_MAXIMUM_MEMORY=4096m'
      - 'JVM_SUPPORT_RECOMMENDED_ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
      - HAZELCAST_GROUP_NAME=${BITBUCKET_HAZELCAST_GROUP_NAME}
      - 'HAZELCAST_GROUP_PASSWORD=1234'
      - 'HAZELCAST_NETWORK_MULTICAST=true'
      - XAUTHORITY=${XAUTH}
      - DISPLAY
  proxy:
    depends_on:
      - bitbucket_node_1
      - bitbucket_node_2
    image: haproxy:2.3
    networks:
      - bbnet
    ports:
        - ${BITBUCKET_PROXY_PORT}:${BITBUCKET_PROXY_PORT}
    volumes:
        - ${BITBUCKET_HAPROXY_CONFIG}:/usr/local/etc/haproxy/haproxy.cfg

  postgresql:
    image: postgres:11
    networks:
      - bbnet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    ports:
      - ${BITBUCKET_HOST_DB_PORT}:5432
    environment:
      - POSTGRES_USER=${BITBUCKET_DB_USER}
      - POSTGRES_PASSWORD=${BITBUCKET_DB_PASS}
      - 'POSTGRES_DB=bitbucketdb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
volumes:
  postgresqldata:
    external: false

networks:
  bbnet:
    driver: bridge
